### ISSUE TITLE
Second hand

### ISSUE THREAD

**Issue by stefanheule** [stefanheule/obsidian#1]
An optional second hand (off by default due to battery usage).

**Comment by yoshimov** [comment]
:+1:
I prefer to use small ball for the second hand like TH10c. There is no need to avoid the hand if it is a ball.

**Comment by tavisaman** [comment]
To save battery please consider to make the resolution of the second hat variable. In other words instead of 1 second screen update, the user could set 5, 10, 15 or 30 seconds update, or it could be battery level dependent.
An alternative to the second hand or a small ball would be a small pie chart in one of the lower corners.

**Comment by stefanheule** [comment]
This has been implemented in 3.0.
